# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iridium Browser
email: iridium@lists.inai.de
description: > # this means to ignore newlines until "baseurl:"
  The iridiumbrowser is based on the Chromium code base. 
  All modifications enhance the privacy of the user and make sure that the 
  latest and best secure technologies are used.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iridiumbrowser.de" # the base hostname & protocol for your site

collections:
  - marquee
  - home
  - features
  - manifest
  - about
  - logos
  - contribute
  - footer
  
gems:
  - jekyll-sitemap
  
# Build settings
markdown: kramdown